# Generated by Django 4.1.4 on 2023-01-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('price_per_night', models.PositiveIntegerField(help_text='정수만 입력가능', verbose_name='price')),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=140)),
                ('pet_allow', models.BooleanField(default=True, verbose_name='Pet_Allowed')),
            ],
        ),
    ]
